#!/usr/bin/python

import subprocess, sys, json

if __name__ == '__main__':
   process =  subprocess.Popen(['remctl', 'sql.mit.edu', 'database', 'create', sys.argv[1], sys.argv[2]], stdout=subprocess.PIPE)
   output = process.communicate()
   parsed = json.loads(output[0])
   if parsed['status'] != 0:
      print "Error!  Status was %d.  %s." % (parsed['status'], parsed['error'],)
   else:
      print "Success!  Created %s." %(parsed['db_name'])
