#!/usr/bin/python

import json
import string
import subprocess
import sys
import traceback

HOST = 'sql.mit.edu'

def main():
   if len(sys.argv) != 2:
      print >> sys.stderr, (
         'Incorrect number of arguments\ncreate-database LOCKER+DB_NAME')
      return 1
   _, ldb = sys.argv
   locker, dbname = string.split(ldb, '+', 1)
   process =  subprocess.Popen(['remctl', HOST, 'database', 'create',
                                locker, dbname], stdout=subprocess.PIPE)
   stdout, _  = process.communicate()
   parsed = json.loads(stdout)
   if parsed['status'] != 0:
      print >>sys.stderr, 'Error: %s.' % (parsed['error'],)
      return 1
   return 0

if __name__ == '__main__':
   try:
      sys.exit(main())
   except:
      traceback.print_exc()
      sys.exit(2)
