#!/usr/bin/python

import json
import string
import subprocess
import sys

def getDBName(locker, database, counter):
   template = '%s+%s' % (locker, database)
   if counter:
      template += str(counter)
   return template

if __name__ == '__main__':
   if len(sys.argv) != 2:
      print >>sys.stderr, 'Incorrect number of arguments\nget-next-database LOCKER+DB_NAME'
      sys.exit(1)
   _, ldb = sys.argv
   locker, dbname = string.split(ldb, '+', 1)
   process =  subprocess.Popen(['remctl', 'sql.mit.edu', 'database', 'list', locker],
                               stdout=subprocess.PIPE)
   stdout, _ = process.communicate()
   parsed = json.loads(stdout)
   db_names = [db['name'] for db in parsed['databases']]
   counter = 0
   while True:
      current_db = getDBName(locker, dbname, counter)
      if current_db not in db_names:
         break
      counter += 1
   print current_db
