#!/usr/bin/python

import subprocess, sys, json

if __name__ == '__main__':
   if len(sys.argv) != 2:
      print >> sys.stderr, 'Incorrect number of arguments\nget-next-database LOCKER'
      sys.exit(1)
   locker = sys.argv[1]
   process =  subprocess.Popen(['remctl', 'sql.mit.edu', 'database', 'list', locker],
                               stdout=subprocess.PIPE)
   output = process.communicate()
   parsed = json.loads(output[0])
   dbs = parsed['databases']
   if dbs == []:
      print sys.argv[1]
   db_names = [db['name'] for db in dbs]
   counter = 1
   current_db = '%s%d' % (locker, counter,) 
   while current_db in db_names:
      counter += 1
      current_db = '%s%d' % (locker, counter,)
   print current_db
