#!/usr/bin/python

import json
import os
import subprocess
import sys

ERROR = 255
HOST = 'sql.mit.edu'

def main():
    argc = len(sys.argv)
    if argc == 1:
        sys.argv.append(os.getenv('USER'))
        argc += 1
    if argc != 2:
        print 'get-status: Incorrect number of arguments\nget-status [USER]'
        sys.exit(ERROR)
    _, account = sys.argv
    process = subprocess.Popen(['remctl', HOST, 'account', 'is-auth', account],
                               stdout=subprocess.PIPE)
    stdout, _ = process.communicate()
    parsed = json.loads(stdout)
    if parsed['status'] != 0:
        print >>sys.stderr, 'Error: not authorized'
        sys.exit(ERROR)
    process = subprocess.Popen(['remctl', HOST, 'profile', 'get', account],
                               stdout=subprocess.PIPE)
    stdout, _ = process.communicate()
    parsed = json.loads(stdout)
    status = int(parsed['status'])
    print status
    sys.exit(status)

if __name__ == '__main__':
    main()
