#!/usr/bin/python

import subprocess, sys, json

if __name__ == '__main__':
    process = subprocess.Popen(['remctl', 'sql.mit.edu', 'account', 'is-auth', sys.argv[1]], stdout=subprocess.PIPE)
    output = process.communicate()
    parsed = json.loads(output[0])
    if parsed['status'] != 0:
	print 'Error; not authorized to check locker'
    process = subprocess.Popen(['remctl', 'sql.mit.edu', 'profile', 'get', sys.argv[1]], stdout=subprocess.PIPE)
    output = process.communicate()
    parsed = json.loads(output[0])
    print parsed['status']
