#!/usr/bin/env python

import ConfigParser
import os
import sys

HOST = 'sql.mit.edu'
USER = os.getenv('USER');
HOME = '/mit/%s' % (USER,)
CONFIG = '%s/.sql/my.cnf' % (HOME,)

mycnf = ConfigParser.RawConfigParser()
mycnf.read(CONFIG)

host = mycnf.get('client', 'host')
user = mycnf.get('client', 'user')
password = mycnf.get('client', 'password')

print "%s\t%s\t%s" % (host, user, password)
sys.exit(0)
