#!/bin/sh

mkdir $lroot/.sql 2>/dev/null
fs sa $lroot/.sql system:anyuser none
fs sa $lroot/.sql system:authuser none
fs sa $lroot/.sql daemon.scripts write
fs sa $lroot/.sql daemon.sql write
rm -f $lroot/.sql/my.cnf $lroot/.my.cnf

cat <<EOF > $lroot/.sql/my.cnf
[client]
host=sql.mit.edu
user=$sqluser
password=$sqlpass
EOF

ln -nfs .sql/my.cnf $lroot/.my.cnf 2>/dev/null
